# Project: maze
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe -D__DEBUG__
CC   = gcc.exe -D__DEBUG__
WINDRES = windres.exe
RES  = maze_private.res
OBJ  = maze.o MazeMap.o MazePerson.o MyMazeMap.o MyMazer.o $(RES)
LINKOBJ  = maze.o MazeMap.o MazePerson.o MyMazeMap.o MyMazer.o $(RES)
LIBS =   -g3 
INCS = 
CXXINCS = 
BIN  = maze.exe
CXXFLAGS = $(CXXINCS)   -g3
CFLAGS = $(INCS)   -g3
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before maze.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "maze.exe" $(LIBS)

maze.o: maze.cpp
	$(CPP) -c maze.cpp -o maze.o $(CXXFLAGS)

MazeMap.o: MazeMap.cpp
	$(CPP) -c MazeMap.cpp -o MazeMap.o $(CXXFLAGS)

MazePerson.o: MazePerson.cpp
	$(CPP) -c MazePerson.cpp -o MazePerson.o $(CXXFLAGS)

MyMazeMap.o: MyMazeMap.cpp
	$(CPP) -c MyMazeMap.cpp -o MyMazeMap.o $(CXXFLAGS)

MyMazer.o: MyMazer.cpp
	$(CPP) -c MyMazer.cpp -o MyMazer.o $(CXXFLAGS)

maze_private.res: maze_private.rc 
	$(WINDRES) -i maze_private.rc --input-format=rc -o maze_private.res -O coff 
